DROP DATABASE IF EXISTS ClassArchives;
CREATE DATABASE ClassArchives;

DROP USER IF EXISTS admin;
CREATE USER admin WITH PASSWORD 'pass';

GRANT ALL PRIVILEGES ON DATABASE ClassArchives TO postgres;
